# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-07-27 20:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appointmentApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task', models.CharField(max_length=255)),
                ('date', models.DateField(default=False, null=True)),
                ('time', models.TimeField()),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Missed', 'Missed'), ('Done', 'Done')], max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user_appointments', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='appointmentApp.User')),
            ],
        ),
    ]
